/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mao_arithmatic_Arithmatic */

#ifndef _Included_mao_arithmatic_Arithmatic
#define _Included_mao_arithmatic_Arithmatic
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     mao_arithmatic_Arithmatic
     * Method:    MyBOWMatch
     * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/List;)Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_mao_arithmatic_Arithmatic_MyBOWMatch
    (JNIEnv*, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
